function PlotInfo = psoemPlotInfo
%
% Copyright (c) 2016 Xin (Ben) Kang
%

% default configuration
PlotInfo = struct( ...
	'Viz', true, ...
	'Itr', [], ...
	'Q', [], ...
	'param', [], ...
	'Sigma', [], ...
	'Image', [], ...
	'ImgPts', [], ...
	'Y_prj', [], ...
	'Pmn', [], ...
	'DrawCrrpMap', true, ...
	'DrawLegend', true, ...
	'ShowPointNumber', false, ...
	'done', false ...
);


%% EOF
